### PR TITLE
Update async & request

### PR DESCRIPTION
**Pull request by josephpage**
Async from 0.9.0 to 1.4.1 [Changelog](https://github.com/caolan/async/blob/master/CHANGELOG.md) - bug fixes and new features, no breaking changes

Request from 2.58.0 to 2.60.0 [Changelog](https://github.com/request/request/blob/master/CHANGELOG.md) - bug fixes

Thanks !

### CODE REVIEW

**Comment by davesouthey** [comment]
Any chance of getting this merged in for the next release? Would be nice to catch the dependencies up with google-auth-library-nodejs.

**Comment by davesouthey** [comment]
@josephpage "iojs" isn't supported by nvm any more. Maybe best to replace with "v4" or "v4.2".

**Comment by josephpage** [comment]
Thanks @davesouthey. Fixed.
cc @ryanseys

**Comment by ryanseys** [comment]
Can you squash and I'll make sure it goes out in the next release

**Comment by josephpage** [comment]
Squashed as you want @ryanseys

**Comment by davesouthey** [comment]
Thanks @josephpage and @ryanseys

**Pull request merged**
