### PR TITLE
Compile the package before publishing it on npm with the npm prepare script.

### PR DESCRIPTION
**Pull request by etnbrd**
Fixes #<issue_number_goes_here> (it's a good idea to open an issue first for discussion)

- [x] `npm test` succeeds
- [x] Pull request has been squashed into 1 commit
- [x] I did NOT manually make changes to anything in `apis/`
- [x] Code coverage does not decrease (if any source code was changed)
- [x] Appropriate JSDoc comments were updated in source code (if applicable)
- [x] Approprate changes to readme/docs are included in PR

### CODE REVIEW

**Comment by etnbrd** [comment]
I signed it!

**Comment by JustinBeckwith** [comment]
This LGTM

**Comment by etnbrd** [comment]
btw, I believe travis was failing before this commit.

**Comment by jmdobry** [comment]
obviated by #792 no?

**Comment by JustinBeckwith** [comment]
Yup, the prepare npm script takes care of things.  Thanks for the PR though!

**Pull request closed without merging**
