### PR TITLE
File encoding on download

### LINKED ISSUE #501: Drive download returning token JSON object
Hello, I'm having a problem downloading from the Drive using this API (v3). The data returned from the API is of the form: 

    {
      "access_token" : "HUGE_TOKEN_STRING",
      "token_type" : "Bearer",
      "expires_in" : 3600
    }

My code is roughly as follows (parts ommited due to confidentiality reasons):

      var buffer = new Buffer(0);
      drive.files.get({
          auth: auth,
          alt: 'media',
          fileId: id,
      })
      .on('error', function (err) {
        logger.error("Error " + err);
        callback(err, null);
      })
      .on('data', function (data) {
        logger.info("Got data!");
        buffer = Buffer.concat([buffer, data], buffer.length + data.length);
      })
      .on('end', function () {
        logger.info("End event!");
        callback(null, buffer);
      });

auth is an object created using a derivation of this example: https://developers.google.com/drive/v3/web/quickstart/nodejs#step_3_set_up_the_sample

Am I doing something wrong, or has the API changed somehow?

### PR DESCRIPTION
**Pull request by SamuelePilleri**
Fixes #501 

- [ ] `npm test` succeeds
- [x] Pull request has been squashed into 1 commit
- [ ] I did NOT manually make changes to anything in `apis/`
- [x] Code coverage does not decrease (if any source code was changed)
- [x] Appropriate JSDoc comments were updated in source code (if applicable)
- [ ] Approprate changes to readme/docs are included in PR

Added ability to specify file enconding when downloading files from Google Drive.

This also fixes #501 by applying the following:
```javascript
drive.files.get({
  fileId: myFileId,
  alt: "media",
  encoding: null
}, function(err, buffer) {
  // Stuff
  dest.write(buffer);
  dest.close();
});
```

### CODE REVIEW

**Comment by SamuelePilleri** [comment]
I signed it!

**Comment by jmdobry** [comment]
The contents of `apis/` are auto-generated every time a new release of this library is created, you can't modify anything in `apis/`.

If something needs to be fixed it needs to be fixed upstream, probably here: https://github.com/google/google-auth-library-nodejs

**Comment by SamuelePilleri** [comment]
Oh, ok.

This modification, however, falls under `/apis/drive` path so, where should I bring this mod to? I can't find any drive-related source in the link you gave me.

**Comment by jmdobry** [comment]
To be honest, I'm not really sure. I need to spend some time reading the source code to figure it out.

**Comment by SamuelePilleri** [comment]
Ok, thank you very much, let me know when you have news!

Btw, if you believe there's a better and more _design-like_ way to do it and solve #501, please let me know, it's good to learn :)

**Comment by SamuelePilleri** [comment]
I guess I can close this after #623.

**Comment by jmdobry** [comment]
@SamuelePilleri Have you tried #623 in 12.4.0?

**Comment by SamuelePilleri** [comment]
Yes, it works.

**Pull request closed without merging**
