### PR TITLE
Generate declaration files

### PR DESCRIPTION
**Pull request by notVitaliy**
Generate typescript declaration files.

- [x] `npm test` succeeds
- [x] Pull request has been squashed into 1 commit
- [x] I did NOT manually make changes to anything in `apis/`
- [x] Code coverage does not decrease (if any source code was changed)
- [x] Appropriate JSDoc comments were updated in source code (if applicable)
- [x] Approprate changes to readme/docs are included in PR

### CODE REVIEW

**Comment by jmdobry** [comment]
@JustinBeckwith Looks good to you?

**Comment by jloveridge** [comment]
Please add a `types` property to `package.json` as well so that types are automatically discovered when the package is installed.

**Comment by martywins** [comment]
@notVitaliy Thanks for opening this!! Super keen for types!! 👍

**Comment by JustinBeckwith** [comment]
This looks good!  Just need to go add the `types` property to the `package.json` :) . Test failures look to be unrelated.

**Comment by martywins** [comment]
@JustinBeckwith thanks for your speedy reply!  Assuming this gets merged soon, how long til the next release?

**Comment by JustinBeckwith** [comment]
Thanks for the PR!

**Pull request merged**
