### PR TITLE
release 25.0.0

### PR DESCRIPTION
**Pull request by alexander-fenster**
Releasing v25.0.0.

### CODE REVIEW

**Comment by JustinBeckwith** [comment]
Right now something is up with Travis, but even before that - CI seemed to be broken for Node.js 4 and 6.  Usually this means there was an update in some sort of transitive dependency, and not having a package-lock.json (like we do in 8 and 9) has bitten us.  I haven't had time to debug the issue, but I think that's something we should do before cutting a release.

**Comment by alexander-fenster** [comment]
I'll take a look. Also, do you mind changing travis to circle for this repo? I can do that.

**Comment by JustinBeckwith** [comment]
I wouldn't mind at all.  Thank you :) That and setting up automatic releases were on the list.

**Comment by alexander-fenster** [comment]
OK :)

**Pull request merged**
