### PR TITLE
8.0.0

### PR DESCRIPTION
**Pull request by jmdobry**
###### Breaking changes
- Removed `cloudbuild` `v1` API
- Removed `cloudlatencytest` `v2` API
- Removed `drive` `v1` API

###### Backwards compatible changes
- Added `dns` `v2beta1` API
- Added `routers.preview` to `compute` `alpha` API
- Added `instances.startWithEncryptionKey` to `compute` `v1` API
- Added `routers.aggregatedList` to `compute` `v1` API
- Added `routers.delete` to `compute` `v1` API
- Added `routers.get` to `compute` `v1` API
- Added `routers.getRouterStatus` to `compute` `v1` API
- Added `routers.insert` to `compute` `v1` API
- Added `routers.list` to `compute` `v1` API
- Added `routers.patch` to `compute` `v1` API
- Added `routers.updated` to `compute` `v1` API
- Added `mobileapppanels.get` to `consumersurveys` `v2` API
- Added `mobileapppanels.list` to `consumersurveys` `v2` API
- Added `mobileapppanels.update` to `consumersurveys` `v2` API

### CODE REVIEW

**Comment by abstrctn** [comment]
Hi, I just noticed the change removing the `cloudbuild` API, and am wondering what the reason is for removing it, particularly since that API isn't available through `gcloud-node`.

Thanks!

**Comment by jmdobry** [comment]
I do not know why the API was removed. Every time this library is regenerated, it's built according to the APIs available at https://www.googleapis.com/discovery/v1/apis, and the `cloudbuild` discovery document is definitely gone. It's gone from https://developers.google.com/apis-explorer/ as well.

**Comment by jmdobry** [comment]
However, it looks like the discovery document was moved to https://cloudbuild.googleapis.com/$discovery/rest?version=v1, and https://www.googleapis.com/discovery/v1/apis has not been updated to reflect this change.

In the mean time, with `googleapis` v8.0.0 you can still access the `cloudbuild` like this:

```js
google.discoverApi('https://cloudbuild.googleapis.com/$discovery/rest?version=v1', function (err, cloudbuild) {
  // use cloudbuild
});
```

**Comment by abstrctn** [comment]
Perfect, thank you!

**Pull request merged**
