### PR TITLE
Drive sample bug fixes  (#2)

### LINKED ISSUE #1060: Changes required in drive api sample
The updated sample for downloading a file using drive API needs some changes(minor). I am listing those here-
1. The scope mentioned in the current sample does not allow files to be downloaded. It allows read-only access to the metadata and not the content.
2. Currently, the file Id has been hardcoded. The file id should be passed as an argument (according to this [readme](https://github.com/google/google-api-nodejs-client/blob/master/samples/drive/README.md)).

My current environment-
googleapis @ 27.0.0
node @ 8.9.4
npm @ 5.6.0

Thanks!

### PR DESCRIPTION
**Pull request by samaystops4no1**
Fixes #1060

- [x] `npm test` succeeds
- [x] Pull request has been squashed into 1 commit
- [x] I did NOT manually make changes to anything in `apis/`
- [x] Code coverage does not decrease (if any source code was changed)
- [x] Appropriate JSDoc comments were updated in source code (if applicable)
- [x] Appropriate changes to readme/docs are included in PR

### CODE REVIEW

**Comment by JustinBeckwith** [comment]
👋  greetings, and thanks for the PR!  It looks like some of the sample tests are failing.  Could you try running `make test-samples`, fixing the issue, and pushing again?  Thank you!

**Comment by samaystops4no1** [comment]
Hello,
@JustinBeckwith I have found the issue. To make all the tests succeed, I need to make minor changes in ```build/test/samples/test.samples.drive.js``` file. But I think that this file(or folder) is included in .gitignore. How should I push these changes? Is modifying .gitignore ok?

Thanks !

**Comment by JustinBeckwith** [comment]
Ahh!  We generate our *.js files from TypeScript.  The test you need to modify is `test/samples/test.samples.drive.ts`.   When you run `make build` it will compile that down to JavaScript for you :)  The `.gitignore` change is not needed!

**Comment by samaystops4no1** [comment]
Hello!
@JustinBeckwith The issue is fixed. All the sample-tests and ```npm test``` are passing. These changes are also required for some other samples. I will create a separate issue for those and fix them there.

Thanks!

**Comment by JustinBeckwith** [comment]
Thanks for the PR!  We ended up using this to land #1077, so we're all set now :)

**Pull request closed without merging**
